# AI Provider Configuration
# This file defines available AI providers and their configurations

providers:
  claude:
    name: "claude"
    type: "anthropic"
    description: "Claude by Anthropic - Advanced reasoning and analysis"

    models:
      claude_3_5_sonnet:
        name: "claude-3-5-sonnet-20241022"
        description: "Most capable model for complex tasks"
        context_length: 200000
        cost_per_1k_input: 0.015
        cost_per_1k_output: 0.075

      claude_3_5_haiku:
        name: "claude-3-5-haiku-20241022"
        description: "Fast and efficient model"
        context_length: 200000
        cost_per_1k_input: 0.001
        cost_per_1k_output: 0.005

    configuration:
      api_base: "https://api.anthropic.com"
      api_version: "2023-06-01"
      timeout: 60
      max_retries: 3

    usage:
      builder_crew: true
      project_crews: false
      recommended_for:
        - "strategic_planning"
        - "technical_architecture"
        - "complex_reasoning"
        - "code_review"
        - "ux_design"

  zhipuai:
    name: "zhipuai"
    type: "zhipuai"
    description: "ZhipuAI GLM models - Multimodal AI capabilities"

    models:
      glm_4_6:
        name: "glm-4.6"
        description: "Latest multimodal model"
        context_length: 128000
        cost_per_1k_input: 0.01
        cost_per_1k_output: 0.03

      glm_4:
        name: "glm-4"
        description: "Capable general model"
        context_length: 128000
        cost_per_1k_input: 0.008
        cost_per_1k_output: 0.025

    configuration:
      api_base: "https://open.bigmodel.cn/api/paas/v4"
      timeout: 60
      max_retries: 3

    usage:
      builder_crew: true
      project_crews: false
      recommended_for:
        - "quality_assurance"
        - "infrastructure_management"
        - "deployment_automation"
        - "support_tasks"
        - "multimodal_processing"

  openai:
    name: "openai"
    type: "openai"
    description: "OpenAI GPT models - Versatile and widely adopted"

    models:
      gpt_4_turbo_preview:
        name: "gpt-4-turbo-preview"
        description: "Latest GPT-4 model with improved capabilities"
        context_length: 128000
        cost_per_1k_input: 0.01
        cost_per_1k_output: 0.03

      gpt_4:
        name: "gpt-4"
        description: "Capable model for complex tasks"
        context_length: 8192
        cost_per_1k_input: 0.03
        cost_per_1k_output: 0.06

      gpt_3_5_turbo:
        name: "gpt-3.5-turbo"
        description: "Fast and cost-effective model"
        context_length: 16385
        cost_per_1k_input: 0.0015
        cost_per_1k_output: 0.002

    configuration:
      api_base: "https://api.openai.com/v1"
      api_version: "2023-07-01-preview"
      timeout: 60
      max_retries: 3

    usage:
      builder_crew: false
      project_crews: true
      recommended_for:
        - "general_crew_tasks"
        - "content_generation"
        - "data_analysis"
        - "customer_service"
        - "code_generation"

# Provider Selection Rules
selection_rules:
  builder_crew:
    primary: "claude"
    secondary: "zhipuai"
    fallback_order: ["claude", "zhipuai"]

  project_crews:
    primary: "openai"
    fallback_order: ["openai"]

  task_specific:
    strategic_planning: "claude"
    technical_architecture: "claude"
    ux_design: "claude"
    quality_assurance: "zhipuai"
    infrastructure: "zhipuai"
    general_tasks: "openai"
    creative_tasks: "openai"
    analytical_tasks: "openai"

# Cost Management
cost_management:
  monthly_limits:
    claude: 500.0  # USD
    zhipuai: 300.0
    openai: 1000.0

  daily_limits:
    claude: 20.0
    zhipuai: 15.0
    openai: 50.0

  alerts:
    threshold_80: true
    threshold_90: true
    threshold_100: true

# Performance Metrics
performance_metrics:
  response_time_targets:
    claude: 2.0  # seconds
    zhipuai: 3.0
    openai: 2.5

  success_rate_targets:
    claude: 0.95
    zhipuai: 0.90
    openai: 0.92

  availability_targets:
    claude: 0.99
    zhipuai: 0.98
    openai: 0.99

# Security Configuration
security:
  api_key_storage:
    encryption: true
    rotation_required: true
    audit_logging: true

  data_protection:
    encryption_in_transit: true
    data_retention: "30 days"
    compliance: "GDRL CCPA"

# Monitoring and Alerting
monitoring:
  metrics_to_track:
    - "api_response_time"
    - "error_rate"
    - "token_usage"
    - "cost_accumulation"
    - "success_rate"

  alert_channels:
    - "console"
    - "log_file"
    - "email"  # if configured

  health_checks:
    enabled: true
    interval: 300  # seconds
    timeout: 10

# Backup and Redundancy
backup:
  provider_failover:
    enabled: true
    automatic_switching: true
    manual_override: true

  configuration_backup:
    enabled: true
    frequency: "daily"
    retention: "30 days"

# Development vs Production
environments:
  development:
    cost_limits: 0.5  # 50% of normal limits
    verbose_logging: true
    debug_mode: true

  production:
    cost_limits: 1.0  # Full limits
    verbose_logging: false
    debug_mode: false
    high_availability: true

---
# Usage Instructions

## Builder Crew Configuration
The builder crew uses Claude for primary tasks and ZhipuAI as secondary:
- Claude: Strategic planning, architecture, design
- ZhipuAI: Quality assurance, infrastructure, deployment

## Project Crew Configuration
New project crews use OpenAI by default:
- OpenAI GPT-4 Turbo for complex tasks
- OpenAI GPT-3.5 Turbo for simpler tasks
- Cost-effective and widely supported

## Provider Switching
To switch providers for specific tasks:
1. Update the selection_rules section
2. Modify agent configurations
3. Test with new provider before full deployment

## API Key Management
Set these environment variables:
- ANTHROPIC_API_KEY for Claude
- ZHIPUAI_API_KEY for ZhipuAI
- OPENAI_API_KEY for OpenAI